fix: added keep3r network projects & tags to allo
defi-wonderland/web pull request #125
Opened 2024-10-11 19:21 UTC by oxlumi

- Added keep3r network v2
- Added Sidechain Oracles
- Added Smart Contracts to Allo Tags

2024-10-11 19:48 UTC, 0xShishigami requested changes

2024-10-11 19:48 UTC, 0xShishigami commented on src/data/projects.json
> +      "tags": ["Research", "Smart Contracts", ""],
```suggestion
      "tags": ["Research", "Smart Contracts"],
```

2024-10-14 19:12 UTC, oxlumi commented
Update: also fixed broken links and edit tags from Allo (missing tags).

2024-10-14 19:26 UTC, 0xShishigami approved these changes

2024-10-14 20:40 UTC, 0xArdy approved these changes
lgtm!

2024-10-14 20:42 UTC, Onizuka-wl approved these changes

2024-10-14 20:43 UTC, merged